### ISSUE TITLE
limit access to profiling

### ISSUE THREAD

**Issue by degeri** [decred/dcrpool#214] opened 2020-05-12 10:21 UTC
The current config for profiling leaves the chance that someone might enable it by mistake and expose sensitive information to the public. 

So I propose we either only allow it in localhost or we have the user set another "--insecure-profile=true" config to enable custom hostname. This way they know they are enabling an risky setting.

**Comment by dnldd** [comment] 2020-05-12 11:16
After taking a second look at `--profile` it requires the  that the user be explicit about the exposure the profile endpoint gets. The user would have to explicitly set the profile endpoint  to a publicly accessible ip. Due to that I think we are providing enough limitations and control for that config option.

**Comment by degeri** [comment] 2020-05-12 11:57
The current harness the value is ":6060" it defaults to 0.0.0.0

**Comment by dnldd** [comment] 2020-05-12 12:19
Yeah looks like the issue is with the harness, should not be binding the profiler on all interfaces on port 6060. It should be specifying just the port there: '6060'

**Comment by dnldd** [comment] 2020-05-13 13:40
Resolved by #216.

**Closed by dnldd** 2020-05-13 13:40 UTC
